export const inputItems = [
  {
    name: "name",
    type: "text",
    label: "Name:",
    placeholder: "e.g. John Doe",
    required: "Name: is required",
    pattern: { value: 2, message: "Job must be at least 2 characters." },
  },
  {
    name: "job",
    type: "text",
    label: "Job:",
    placeholder: "e.g. Frontend Developer",
    required: "Job: is required",
  },
  {
    name: "company",
    type: "text",
    label: "Company:",
    placeholder: "e.g. ABC Corp",
    required: "Company: is required",
  },
  {
    name: "location",
    type: "text",
    label: "Location:",
    placeholder: "e.g. New York City",
  },
  {
    name: "email",
    type: "text",
    label: "Email:",
    placeholder: "e.g. user@email.com",
    required: "Email: is required",
    pattern: {
      value: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
      message: "Please enter a valid email address.",
    },
  },
  {
    name: "phone",
    type: "text",
    label: "Phone:",
    placeholder: "e.g. 099-012-3456",
    required: "Phone: is required",
    pattern: {
      value: /^[0-9]{10}$/,
      message: "Please enter a valid 10-digit",
    },
    maxLength: 10,
  },
  {
    name: "salary",
    type: "number",
    label: "Salary:",
    placeholder: "e.g. 50000",
    required: "Salary is required",
    min: { value: 0, message: "Salary cannot be less than zero." },
    max: { value: 1000000, message: "Salary must be realistic." },
  },
  {
    name: "image",
    type: "text",
    label: "Image:",
    placeholder: "Paste image URL",
    className: "hidden",
  },
];

export const imageItems = [
  { id: "avatar1", src: "/avatar/ace.jpg" },
  { id: "avatar2", src: "/avatar/sabo.jpg" },
  { id: "avatar3", src: "/avatar/lufy.jpg" },
  { id: "avatar4", src: "/avatar/sanji.jpg" },
  { id: "avatar5", src: "/avatar/shank.jpg" },
  { id: "avatar6", src: "/avatar/zoro.jpg" },
  { id: "avatar7", src: "/avatar/bepo.jpg" },
  { id: "avatar8", src: "/avatar/brook.jpg" },
  { id: "avatar9", src: "/avatar/chopper.jpg" },
  { id: "avatar10", src: "/avatar/garp.jpg" },
  { id: "avatar11", src: "/avatar/jinbe.jpg" },
  { id: "avatar12", src: "/avatar/koby.jpg" },
  { id: "avatar13", src: "/avatar/rayleigh.jpg" },
  { id: "avatar14", src: "/avatar/mihawk.jpg" },
  { id: "avatar15", src: "/avatar/roger.jpg" },
];
